name: GitHub Actions Demo
on: [ push ]
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm install
      - run: npm run lint
  deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: /
          remote_path: /home/c15464/guural.ru/app
          remote_host: h14.netangels.ru
          remote_user: c15464
          remote_key: ${{ secrets.DEPLOY_KEY }}