name: GitHub Actions Demo
on: [ push ]
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm install
      - run: npm run lint
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Deploy
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete --exclude=".env"
          path: /
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}